stages:
  install-requirements:
    cmd: pip install -r requirements.txt
    deps:
    - requirements.txt
  initialize-accelerate-env:
    cmd: accelerate config default
  train-model:
    cmd: accelerate launch src/model/train_model.py --instance_prompt="a photo of sks dog" --class_prompt="a photo of dog"
    deps:
    - data/dog
    - src/model/train_model.py
    outs:
    - trained_model
    params:
    - params/params.yaml:
        - model_id
        - resolution
    - params/train-params.yaml:


